In [9]:
# antes de empezar importamos la librería de NumPy para poder trabajar con todos sus métodos. 
import numpy as np

Creación y Indexación:


1) Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [10]:
# Crear el array

array_1d = np.random.randint(10,99,50)

print(array_1d)
print ("------------------------------------------------------")
array_1d[4:50:5]

[59 10 23 79 32 18 60 74 49 22 80 29 70 57 85 87 47 25 82 76 94 97 15 63
 45 21 26 36 49 83 73 73 78 70 54 81 21 14 48 78 94 71 23 87 34 90 15 92
 18 93]
------------------------------------------------------


array([32, 22, 85, 76, 45, 83, 54, 78, 34, 93])

2) Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [11]:
array2 = np.random.randint(1,21,30)

print(array2)
print ("------------------------------------------------------")
array2[1:30:2]

[10  4  7  5 15  9 10 12  9  5 16 12  9 12  4  2 14 15  6 20  5 15 13 18
  2 14  7  1 17 13]
------------------------------------------------------


array([ 4,  5,  9, 12,  5, 12, 12,  2, 15, 20, 15, 18, 14,  1, 13])

3) Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [12]:
array_2d = np.random.uniform(0,50, (4,6)).round(2)

print(array_2d)
print ("------------------------------------------------------")
array_2d[3]

[[ 4.13 23.3   1.53  3.5  19.54 26.36]
 [23.01 11.65 11.97 31.33 26.37 43.08]
 [ 0.47 17.66 42.99 30.44 26.2  40.66]
 [46.   49.42 34.13 31.39  0.56 40.96]]
------------------------------------------------------


array([46.  , 49.42, 34.13, 31.39,  0.56, 40.96])

4) BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [13]:
array_3d = np.random.randint(0,101, (2,3,5))

print(array_3d)
array_3d.size

print ("------------------------------------------------------")
array_flat = array_3d.flatten()
print(array_flat)

print ("------------------------------------------------------")

array_flat[2::3] = 0 
print(array_flat)
print ("------------------------------------------------------")

array_reshape = array_flat.reshape(2,3,5)
print(array_reshape)


[[[ 6  2 30 43 71]
  [99 29 58 13 13]
  [ 0 79  4  4 47]]

 [[77 64 66 57 44]
  [74 72 22 25 58]
  [72 79 29 45 51]]]
------------------------------------------------------
[ 6  2 30 43 71 99 29 58 13 13  0 79  4  4 47 77 64 66 57 44 74 72 22 25
 58 72 79 29 45 51]
------------------------------------------------------
[ 6  2  0 43 71  0 29 58  0 13  0  0  4  4  0 77 64  0 57 44  0 72 22  0
 58 72  0 29 45  0]
------------------------------------------------------
[[[ 6  2  0 43 71]
  [ 0 29 58  0 13]
  [ 0  0  4  4  0]]

 [[77 64  0 57 44]
  [ 0 72 22  0 58]
  [72  0 29 45  0]]]


Reshape y Transpose:


1) Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [14]:
array3 = np.random.randint(0,101, (2,3,4))

print(array3)
print ("------------------------------------------------------")
print(array3.size)
print ("------------------------------------------------------")

# Si queremos mantener la cantidad de columnas:
nuevo_array = np.reshape(array3, (6,4))
print(nuevo_array)
print ("------------------------------------------------------")

# Si no queremos mantener la cantidad de columnas:
nuevo1_array = np.reshape(array3, (4,6))
print(nuevo1_array)

[[[60 50 56  1]
  [21 18 30 98]
  [27  5 59 61]]

 [[91 73 38 50]
  [79 57 18  8]
  [44 96 55 56]]]
------------------------------------------------------
24
------------------------------------------------------
[[60 50 56  1]
 [21 18 30 98]
 [27  5 59 61]
 [91 73 38 50]
 [79 57 18  8]
 [44 96 55 56]]
------------------------------------------------------
[[60 50 56  1 21 18]
 [30 98 27  5 59 61]
 [91 73 38 50 79 57]
 [18  8 44 96 55 56]]


2) Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [34]:
d3_array = np.arange(1, 61).reshape(3, 4, 5)

print(d3_array)
print ("------------------------------------------------------")
print(d3_array.size)
print ("------------------------------------------------------")
# Nuevo shape con lo mismo numero de columnas
nuevo2_array = np.reshape(d3_array, (12,5))
print(nuevo2_array)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
------------------------------------------------------
60
------------------------------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]


3) Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [35]:
array_permutado = d3_array.transpose(2, 1, 0)
print("\nArray con ejes permutados (5, 4, 3):\n", array_permutado)


Array con ejes permutados (5, 4, 3):
 [[[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]

 [[ 5 25 45]
  [10 30 50]
  [15 35 55]
  [20 40 60]]]


4) Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

In [36]:
array_permutado2 = d3_array.transpose(0, 2, 1)
print("\nArray con ejes permutados (3,5,4):\n", array_permutado2)


Array con ejes permutados (3,5,4):
 [[[ 1  6 11 16]
  [ 2  7 12 17]
  [ 3  8 13 18]
  [ 4  9 14 19]
  [ 5 10 15 20]]

 [[21 26 31 36]
  [22 27 32 37]
  [23 28 33 38]
  [24 29 34 39]
  [25 30 35 40]]

 [[41 46 51 56]
  [42 47 52 57]
  [43 48 53 58]
  [44 49 54 59]
  [45 50 55 60]]]


5) ¿Qué diferencia existe entre el reshape y el transpose?

* La diferencia principal entre reshape y transpose es cómo cada uno reorganiza un array:

* El **reshape** reorganiza el array 1D en una estructura 2D, pero mantiene el orden secuencial de los elementos.
* Cambia la forma del array ajustando su número de dimensiones o el tamaño de cada dimensión.
* No afecta la orientación de los ejes ni los datos subyacentes.

* El **transpose** intercambia las filas y columnas del array, reorganizando los datos según la orientación de los ejes.
* Permuta los ejes de un array, cambiando la orientación de los datos sin alterar su secuencia en la memoria.
* Cambia la disposición de los datos en función de la ordenación de los ejes.
* Se usa principalmente en arrays con más de una dimensión, ya que reorienta cómo se agrupan y acceden los datos en cada eje.

6) ¿Y entre el transpose y el swapaxes?

**swapaxes**:
* Intercambia solo dos ejes a la vez, sin afectar los demás.
* Este método es útil cuando solo necesitas cambiar la posición de dos ejes específicos en un array multidimensional.

Ambos métodos son útiles en diferentes situaciones:

Usa **transpose** cuando necesitas una reorganización completa de los ejes.
Usa **swapaxes** para intercambiar dos ejes específicos sin cambiar la disposición de los otros ejes.

Funciones Aritméticas y Estadísticas:


1) Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.


In [40]:
matriz_3d = np.random.rand(2,3,5).round(1)
print(matriz_3d)

[[[0.9 0.7 0.2 0.9 0.4]
  [0.7 0.6 0.7 0.8 0.7]
  [0.4 0.1 0.2 0.7 0.5]]

 [[0.1 1.  0.4 0.6 0.8]
  [0.4 0.6 0.9 0.3 0.4]
  [0.3 0.5 0.6 0.  0.8]]]


2) Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

In [61]:
matriz_vacia = np.random.random_sample((2,3,5)).round(1)

print(matriz_vacia)

[[[0.4 0.8 0.3 0.1 0.2]
  [0.3 0.4 0.6 0.1 0.6]
  [0.6 0.6 0.9 0.9 0.8]]

 [[0.7 0.4 0.5 0.2 0.2]
  [0.1 0.7 0.1 0.  0.2]
  [0.1 0.4 0.5 0.7 0.2]]]


In [66]:
# Si el valor del array es igual que la media, se reemplaza por "A".

# Si el valor del array es mayor que la media, se reemplaza por "B".

# Si el valor del array es menor que la media, se reemplaza por "C".

# Si el valor es igual que el máximo, se reemplaza por "D".

# Si el valor es igual que el mínimo, se reemplaza por "E".

media = np.mean(matriz_vacia)
maximo = np.max(matriz_vacia)
minimo = np.min(matriz_vacia)

                                   
                                   

print("La media es:",media)
print("El valor maximo es:",maximo)
print("El valor minimo es:", minimo)

print("------------------------------------------------------------------")
matriznueva = np.where(media == matriz_vacia, "A",
                        np.where(maximo == matriz_vacia, "D",
                            np.where(minimo == matriz_vacia, "E",
                                np.where(media < matriz_vacia, "B","C"))))

print(matriznueva)

La media es: 0.41999999999999993
El valor maximo es: 0.9
El valor minimo es: 0.0
------------------------------------------------------------------
[[['C' 'B' 'C' 'C' 'C']
  ['C' 'C' 'B' 'C' 'B']
  ['B' 'B' 'D' 'D' 'B']]

 [['B' 'C' 'B' 'C' 'C']
  ['C' 'B' 'C' 'E' 'C']
  ['C' 'C' 'B' 'B' 'C']]]
