# Series

### 1. ¿Qué diferencia hay entre una Serie y un DataFrame?

La Serie es unidimensional y el DF bidimensional. 
Todos loss elementos de una Serie tienen que ser del mismo tipo, miemtras que el DF puede contener diferentes tipos de elementos.


In [1]:
import pandas as pd 
import numpy as np

In [9]:
# 2. Momento de trabajar con Series. Contesta a las siguientes preguntas:

# Listas: Valores e Indices

valores = [ 3, 97, 22, 15, 503, 42, 105]

indices = ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']

In [10]:
# A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y 
# la variable indices sean los índices de la Serie.

serie = pd.Series(valores, index=indices)
print(serie)

lunes          3
martes        97
miercoles     22
jueves        15
viernes      503
sabado        42
domingo      105
dtype: int64


In [11]:
# A partir de las dos listas anteriores crea un diccionario usando un bucle for. 
# Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez

diccionario = {}

for indices, valores in zip(indices, valores):
    diccionario[indices] = valores
    
print(diccionario)

{'lunes': 3, 'martes': 97, 'miercoles': 22, 'jueves': 15, 'viernes': 503, 'sabado': 42, 'domingo': 105}


In [12]:

# Crea una Serie con el diccionario creado en el punto anterior.

serie_diccionario = pd.Series(diccionario)
print (serie_diccionario)

lunes          3
martes        97
miercoles     22
jueves        15
viernes      503
sabado        42
domingo      105
dtype: int64


In [13]:
# ¿Qué forma tiene esta última Serie?

serie_diccionario.shape

(7,)

In [14]:
# ¿Qué tipo de datos tiene?

serie_diccionario.dtype

dtype('int64')

In [15]:
# ¿Qué tamaño tiene?

serie_diccionario.size

7

In [16]:
# ¿Cuáles son los índices de la Serie?

serie_diccionario.index

Index(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')

In [17]:
# ¿Y los values?

serie_diccionario.values

array([  3,  97,  22,  15, 503,  42, 105])

In [19]:
# Extrae el valor para el índice "lunes"

print(serie_diccionario['lunes'])

3


In [21]:
# Extrae el valor para el índice "lunes", "martes" y "miércoles".

# Primer corchete (exterior): El primer conjunto de corchetes ([]) se usa para llamar al método loc y pasar los índices como una lista 
# (en este caso, ['lunes', 'domingo']).

# Segundo corchete (interior): El segundo conjunto de corchetes se debe usar para envolver los índices dentro de una lista porque estamos 
# seleccionando múltiples elementos (en lugar de un solo índice). Al pasar una lista de índices, estamos indicándole a loc que queremos obtener 
# los valores de esos índices específicos.

print(serie_diccionario[['lunes', 'martes','miercoles']]) 

lunes         3
martes       97
miercoles    22
dtype: int64


In [25]:
serie_diccionario.loc['lunes':'miercoles']

lunes         3
martes       97
miercoles    22
dtype: int64

In [28]:
# Extrae el valor para el índice "lunes" y "domingo".

serie_diccionario.loc[['lunes','domingo']]

lunes        3
domingo    105
dtype: int64

# DataFrames

In [30]:
# Crea un array de dos dimensiones con 4 filas y 3 columnas.

array = np.random.randint(0, 10, (4, 3))
print(array)

[[4 2 0]
 [3 6 3]
 [3 8 9]
 [0 9 8]]


In [31]:
# Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

df_paises = pd.DataFrame(array, columns=["España", "Francia", "Italia"])
df_paises

España  Francia  Italia
0       4        2       0
1       3        6       3
2       3        8       9
3       0        9       8

In [33]:
# Descarga el archivo "medallas" y carga el DataFrame.

df_medallas = pd.read_csv("medallas.csv", index_col=0)

df_medallas

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [36]:
# Usando el loc extrae todas las columnas de la fila de Tailandia.

df_medallas.loc[7, :]

País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object

In [37]:
# Usando el loc extrae todas las columnas de China e Irán.

df_medallas.loc[[4,9], :]

País  Oro  Plata  Bronce
4          Irán  179    181     197
9  China Taipéi   99    144     276

In [38]:
# Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

df_medallas.loc[[4,9], ['Oro', 'Plata', 'Bronce']]

Oro  Plata  Bronce
4  179    181     197
9   99    144     276

In [40]:
# Usando el iloc extrae la información de la India. Devolved todas las columnas.

df_medallas.iloc[5, :]

País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object

In [42]:
# Usando el iloc extrae todas las columnas de los paises que estén en posición impar. 
# La primera que nos tendría que salir es Japón y la última Corea del Norte.

paises_impares = df_medallas.iloc[1::2, :]
paises_impares

País   Oro  Plata  Bronce
2             Japón  1032   1037     985
4              Irán   179    181     197
6             India   154    202     315
8         Indonesia   112    131     240
10  Corea del Norte    91    120     235

In [43]:
# Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

paises_impares_medallas = df_medallas.iloc[1::2, :][["Oro", "Plata", "Bronce"]]
paises_impares_medallas

Oro  Plata  Bronce
2   1032   1037     985
4    179    181     197
6    154    202     315
8    112    131     240
10    91    120     235

In [44]:
# Contesta a las siguientes preguntas:

# ¿Qué país consiguió más de 200 medallas de oro? 

mas_de_200_oro = df_medallas[df_medallas['Oro'] > 200]
display(mas_de_200_oro)

País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827

In [45]:
# ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

mas_200_oro_1000_plata = df_medallas[(df_medallas['Oro'] > 200) & (df_medallas['Plata'] > 1000)]
display(mas_200_oro_1000_plata)

País   Oro  Plata  Bronce
2  Japón  1032   1037     985

In [46]:
# ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

mas_200_oro_o_700_bronce = df_medallas[(df_medallas['Oro'] > 200) | (df_medallas['Bronce'] > 700)]
display(mas_200_oro_o_700_bronce)

País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827

In [47]:
# Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

df_medallas['total'] = df_medallas['Oro'] + df_medallas['Plata'] + df_medallas['Bronce']
display(df_medallas)

País   Oro  Plata  Bronce  total
1             China  1473    994     720   3187
2             Japón  1032   1037     985   3054
3     Corea del Sur   745    663     827   2235
4              Irán   179    181     197    557
5        Kazajistán   155    158     224    537
6             India   154    202     315    671
7         Tailandia   132    175     278    585
8         Indonesia   112    131     240    483
9      China Taipéi    99    144     276    519
10  Corea del Norte    91    120     235    446